# Generated by Django 3.0.3 on 2020-02-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cv',
            field=models.ImageField(default='default.png', upload_to='about'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(default='default.png', upload_to='about'),
        ),
    ]
