# Generated by Django 3.0.3 on 2020-02-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200215_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
    ]
